import turtle

def draw_house():
    t = turtle.Turtle()
    t.speed(3)
    t.penup()
    t.goto(-50, -50)
    t.pendown()
    t.forward(100)
    t.left(90)
    t.forward(100)
    t.left(45)
    t.forward(70)
    t.left(90)
    t.forward(70)
    t.left(45)
    t.forward(100)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(50)
    t.right(90)
    t.forward(50)
    t.right(90)
    t.forward(50)
    t.hideturtle()
    turtle.done()

draw_house()
